# Generated by Django 4.2.4 on 2023-08-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventsList',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=50)),
                ('event_start_date', models.DateField()),
                ('event_end_date', models.DateField()),
                ('event_img', models.ImageField(upload_to='images/')),
                ('event_description', models.CharField(max_length=280)),
            ],
        ),
        migrations.CreateModel(
            name='PresentationEvents',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=50)),
                ('event_start_date', models.DateField()),
                ('event_end_date', models.DateField()),
                ('event_img', models.CharField(max_length=100)),
                ('event_description', models.CharField(max_length=280)),
            ],
        ),
    ]
