# Generated by Django 4.2.4 on 2023-08-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventCelebration', '0002_remove_presentationevents_event_start_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PresentationEvents',
        ),
    ]
