# Generated by Django 4.2.4 on 2023-08-10 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventCelebration', '0004_presentationevents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PresentationEvents',
        ),
    ]
