# Generated by Django 4.2.4 on 2023-08-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventCelebration', '0006_presentationevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationevents',
            name='presentations_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
